### ISSUE TITLE
Installation failed due to missing component

### ISSUE THREAD

**Issue by elfez** [Bluegrams/PinWin#5]
Just tried to to install 0.2.2 using the `PinWinSetup_Updated.msi` installer but it failed. The installer log contains:

`Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: KillRunningProcess, location: C:\Program Files (x86)\Bluegrams\PinWin\, command: taskkill /f /im PinWin.exe /fi "memusage gt 2" 
=== Logging stopped: 19/05/2020  09:47:35 ===
`

Not sure if me only having .Net 4.8 installed is the issue?

**Comment by alxnull** [comment]
Hi, thanks for reporting. I don't think this issue is related to .NET framework. Could you try if installing the [unpatched version of the installer for v.0.2.2](https://sourceforge.net/projects/pinwin/files/v.0.2.2/PinWinSetup.msi/download) works without issues? (Please uninstall all other versions of PinWin first.)

**Comment by elfez** [comment]
Yup, the original version of 0.2.2 installs fine.

**Comment by alxnull** [comment]
Since there have been [other](https://github.com/Bluegrams/PinWin/issues/4) [issues](https://sourceforge.net/p/pinwin/discussion/general/thread/46b1f692ec/) related to the installer, I decided to rebuild it completely. You may try out if [the newest version](https://sourceforge.net/projects/pinwin/files/v.0.2.2/PinWinSetup_Updated_v2.msi/download) of the setup works for you.

**Comment by elfez** [comment]
That version also installs fine. Thanks for fixing.
